events {
    worker_connections 1024;
}

http {
  upstream orbit_gateway {
    server gateway:3000;
  }

  server {
    listen 80;

    # All traffic goes through Orbit gateway
    location / {
      proxy_pass         http://orbit_gateway;
      proxy_http_version 1.1;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header   Connection        "";
      proxy_read_timeout 30s;
    }
  }
}